decklist('oracle', [
    'Balustrade Spy',
    'Balustrade Spy',
    'Balustrade Spy',
    'Balustrade Spy',
    'Undercity Informer',
    'Undercity Informer',
    'Undercity Informer',
    'Undercity Informer',
    'Narcomoeba',
    'Narcomoeba',
    'Narcomoeba',
    'Narcomoeba',
    'Dread Return',
    'Dread Return',
    'Thassa\'s Oracle',
    'Thassa\'s Oracle',
    'Grim Monolith',
    'Grim Monolith',
    'Grim Monolith',
    'Grim Monolith',
    'Wild Cantor',
    'Wild Cantor',
    'Wild Cantor',
    'Manamorphose',
    'Manamorphose',
    'Lion\'s Eye Diamond',
    'Dark Ritual',
    'Dark Ritual',
    'Dark Ritual',
    'Dark Ritual',
    'Tinder Wall',
    'Tinder Wall',
    'Mox Opal',
    'Rite of Flame',
    'Rite of Flame',
    'Rite of Flame',
    'Chrome Mox',
    'Chrome Mox',
    'Chrome Mox',
    'Chrome Mox',
    'Lotus Petal',
    'Lotus Petal',
    'Lotus Petal',
    'Lotus Petal',
    'Summoner\'s Pact',
    'Summoner\'s Pact',
    'Summoner\'s Pact',
    'Summoner\'s Pact',
    'Chancellor of the Tangle',
    'Chancellor of the Tangle',
    'Chancellor of the Tangle',
    'Chancellor of the Tangle',
    'Elvish Spirit Guide',
    'Elvish Spirit Guide',
    'Elvish Spirit Guide',
    'Elvish Spirit Guide',
    'Simian Spirit Guide',
    'Simian Spirit Guide',
    'Simian Spirit Guide',
    'Simian Spirit Guide'
]).
decklist('TabaDonk', [
    'Thassa\'s Oracle', %formerly 1 dragon breath 1 sutured ghoul
    'Thassa\'s Oracle',
    'Tinder Wall',
    'Tinder Wall',
    'Tinder Wall',
    'Tinder Wall',
    'Narcomoeba',
    'Narcomoeba',
    'Narcomoeba',
    'Elvish Spirit Guide',
    'Elvish Spirit Guide',
    'Elvish Spirit Guide',
    'Elvish Spirit Guide',
    'Simian Spirit Guide',
    'Simian Spirit Guide',
    'Simian Spirit Guide',
    'Simian Spirit Guide',
    'Undercity Informer',
    'Undercity Informer',
    'Undercity Informer',
    'Undercity Informer',
    'Balustrade Spy',
    'Balustrade Spy',
    'Balustrade Spy',
    'Balustrade Spy',
    'Chancellor of the Tangle',
    'Chancellor of the Tangle',
    'Pact of Negation', 
    'Pact of Negation', 
    'Pact of Negation', 
    'Pact of Negation', 
    'Summoner\'s Pact',
    'Summoner\'s Pact',
    'Summoner\'s Pact',
    'Summoner\'s Pact',
    'Cabal Therapy',
    'Cabal Therapy',
    'Dark Ritual',
    'Dark Ritual',
    'Dark Ritual',
    'Dark Ritual',
    'Manamorphose',
    'Manamorphose',
    'Manamorphose',
    'Manamorphose',
    'Dread Return',
    'Unmask',
    'Unmask',
    'Unmask',
    'Unmask',
    'Chrome Mox',
    'Chrome Mox',
    'Chrome Mox',
    'Chrome Mox',
    'Lotus Petal',
    'Lotus Petal',
    'Lotus Petal',
    'Lotus Petal',
    'Bridge from Below',
    'Bridge from Below'
]).
decklist('-jax-', [
    'Thassa\'s Oracle', %formerly 1 lotleth giant
    'Wild Cantor',
    'Narcomoeba',
    'Narcomoeba',
    'Narcomoeba',
    'Narcomoeba',
    'Elvish Spirit Guide',
    'Elvish Spirit Guide',
    'Elvish Spirit Guide',
    'Elvish Spirit Guide',
    'Simian Spirit Guide',
    'Simian Spirit Guide',
    'Simian Spirit Guide',
    'Simian Spirit Guide',
    'Undercity Informer',
    'Undercity Informer',
    'Undercity Informer',
    'Undercity Informer',
    'Balustrade Spy',
    'Balustrade Spy',
    'Balustrade Spy',
    'Balustrade Spy',
    'Street Wraith',
    'Street Wraith',
    'Street Wraith',
    'Chancellor of the Annex',
    'Chancellor of the Annex',
    'Chancellor of the Annex',
    'Chancellor of the Annex',
    'Pact of Negation', 
    'Pact of Negation', 
    'Pact of Negation', 
    'Pact of Negation', 
    'Summoner\'s Pact',
    'Summoner\'s Pact',
    'Summoner\'s Pact',
    'Summoner\'s Pact',
    'Cabal Therapy',
    'Cabal Therapy',
    'Dark Ritual',
    'Dark Ritual',
    'Dark Ritual',
    'Dark Ritual',
    'Cabal Ritual',
    'Cabal Ritual',
    'Cabal Ritual',
    'Cabal Ritual',
    'Manamorphose',
    'Manamorphose',
    'Manamorphose',
    'Manamorphose',
    'Dread Return',
    'Chrome Mox',
    'Chrome Mox',
    'Chrome Mox',
    'Chrome Mox',
    'Lotus Petal',
    'Lotus Petal',
    'Lotus Petal',
    'Lotus Petal'
]).
